### ISSUE TITLE
Composer Requirements

### ISSUE THREAD

**Issue by gbuckingham89** [wa0x6e/Fresque#51]
Are the composer requirements for Fresque up-to-date?

I don't seem to be able to install it via Composer / Packagist - I can't be using `chrisboulton/php-resque` - only `kamisama/php-resque-ex` - is this expected? How up-to-date is your fork kept with Chris' version?

Also, if I use the latest version of `kamisama/php-resque-ex` (1.3.0), I'm unable to install Fresque; I get the following error:

```
Problem 1
    - Installation request for fresque/fresque 1.3.0 -> satisfiable by fresque/fresque[1.3.0].
    - fresque/fresque 1.3.0 requires kamisama/php-resque-ex ~1.2.5 -> no matching package found.
```

Any help/ advice is much appreciated!

**Comment by kamisama** [comment]
Can you try again with version 1.3.1 ?
